### ISSUE TITLE
Changing experiment state to finished in ExperimentRun

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/hypgen#4]
Right now we have `ExperimentRun` responsible for starting all hypgen processes. It also responsible for changing DAP `Experiment` status into error when any exception occurs. Unfortunately logic responsible for setting `Experiment` status into finished (when everything went fine and results are generated) is located somewhere else (inside `hyperflow` workflow?). 

My question is as follow: Is it possible to move logic responsible for setting `Experiment` status into finished into `ExperimentRun`?

/cc @ismop/hypgen-dev-team

**Comment by mpawlik** [comment]
Seems legit, we can get result as a return code or last line (if it's json).
